version: "3.7"

services:
  mtsa:
    build: ./containers/mtsa
    container_name: mtsa
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "2000:2000"
    volumes:
      - ./mtsa-data:/opt/
    working_dir: /opt/
    networks:
      - node-red-net
    tty: true

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red-data:/data

networks:
  node-red-net:
